In [5]:
print("hello")
#开始学习numpy,里面的array的元素需要同质性，就是数据类型需要一致
# 所以不同的数据类型，会转变成为相同的数据类型
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(f"数组形状：{arr.shape},数组维度：{arr.ndim},数组元素个数：{arr.size},数组元素类型:{arr.dtype}")

hello
[1 2 3 4 5]
数组形状：(5,),数组维度：1,数组元素个数：5,数组元素类型:int64


In [ ]:
# ndarray的创建
list=[1,2,34,68]
arr1=np.array(list,dtype=np.float64)# 可以使用dtype指定数据类型
print(arr1)
# 使用copy也可以创建一模一样的数组，互不影响
arr2=np.copy(arr1)
arr2[1]=0
print(arr1,arr2,sep="->")


[ 1.  2. 34. 68.]
[ 1.  2. 34. 68.]->[ 1.  0. 34. 68.]


In [ ]:
#预定义形状比如全0，全1，未初始化，固定值
arr=np.zeros((2,4),dtype=np.int32)#两个括号
print(arr)

arr=np.ones((2,4),dtype=np.int32)#两个括号
print(arr)

arr=np.empty((2,5))
print(arr)

# 指定数字填满，使用full函数即可
arr=np.full((3,4),2026)
print(arr)
# 还有一些函数就是加了个后缀like，就是形状一样，但是比如说full的话，就可以自由填充数值

[[0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]]
[[nan  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [21]:
#等差数列，使用arange函数实现，和range类似，也就是前闭后开,是arange不是arrange
arr=np.arange(1,10,1)# 也是start，stop，step的性质
print(arr)

#等间隔数列，就是从开始到结束，包含结束，最后取几份即可
arr=np.linspace(1,10,5)# 最后一个数字就是代表有几个数字，间隔数会-1
print(arr)

# 对数间隔数列（其实我也觉得是指数间隔数列）
arr=np.logspace(0,4,3,base=2)# 其中base指的是以谁为底,依旧是左闭右闭，最后一个数字就是会分成几份
print(arr)


[1 2 3 4 5 6 7 8 9]
[ 1.    3.25  5.5   7.75 10.  ]
[ 1.  4. 16.]


In [28]:
#矩阵,大于等于三维的都叫做张量
#特殊矩阵的构造，包括单位矩阵以及对角矩阵，对称矩阵
arr=np.eye(3,4,dtype=int)# 因为单位矩阵一定是方阵，所以只用写一个数字,但是计算机里面好像可以行列不同
print(arr)

# 对角矩阵
arr=np.diag([2,3,4,7])# 中间的元素，需要自己填写，元素个数就是行列数
print(arr)

# 随机数组,例如生成0-1的随机浮点数的数组（均匀分布）

# rand函数在random包下，所以还得嵌套一层
arr=np.random.rand(3,4)# 也是可以指定数组形状
print(arr)

#生成指定范围区间的随机浮点数,使用uniform
arr=np.random.uniform(3,6,(4,5))# 前面两个数字就是指定范围,后面就是指定形状
print(arr)


[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]
[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 7]]
[[0.15387522 0.87314888 0.26967211 0.16686697]
 [0.50427738 0.03114591 0.45157333 0.15597739]
 [0.73999964 0.50957513 0.41320283 0.08028111]]
[[4.49439396 3.10558144 4.84884627 3.03891836 5.13646547]
 [5.16774311 4.82592217 3.00443669 3.42637047 3.56184477]
 [5.24432206 4.08734697 3.55550917 4.58285869 4.15575318]
 [5.56853358 4.79370399 3.21645098 5.40241952 5.05811526]]


In [ ]:
#生成指定范围区间的随机整数,使用randint
arr=np.random.randint(3,6,(4,5))# 前面两个数字就是指定范围,后面就是指定形状
print(arr)

#正态分布randn(-3到3之间)
arr=np.random.randn(3,6)
print(arr)

#设置随机种子，怎么说呢，就是每个种子对应的随机数值都是一定的
np.random.seed(42)# 使用的是括号不是=号
arr=np.random.randint(2,30,(5,6))
print(arr)

[[5 3 5 3 5]
 [5 3 3 5 4]
 [3 4 4 4 3]
 [4 3 4 5 5]]
[[ 1.13022819  0.37311891 -0.38647295 -1.15877024  0.56611283 -0.70445345]
 [-1.3779393  -0.35311665 -0.46146572  0.06665728 -0.17628566  1.20089277]
 [ 0.69839894 -0.17162884 -0.90718658  1.18862573  0.78553212  2.65601009]]
[[104 272 108  73 190  22]
 [104 123 216  89 101 153]
 [132 151 259 295 193 278]
 [162  23 254 237  50  60]
 [171 189 272 191 176  52]]


In [ ]:
# 数组索引与切片,普通的切片就是之前讲过了，也是左闭右开即可
# 但是还存在一个bool索引，很方便
arr=np.random.randint(0,100,20)
print(arr)
print(arr[arr>10])# 注意:这就是bool索引,但是是在中括号里面又使用了arr，也算作条件索引，可以使用&或者|来列举多种条件

[70 43  7 46 34 77 80 35 49  3  1  5 53  3 53 92 62 17 89 43]
[70 43 46 34 77 80 35 49 53 53 92 62 17 89 43]


In [60]:
# 二维数组的切片
arr=np.random.randint(0,100,(4,6))
print(arr)
print(arr[1][3])
print(arr[1,3])
#切片操作，也是左闭右开,只不过二维数组需要加上一个逗号分隔开来,依旧是start,end,step
print(arr[1:,:])
print(arr[:2,:3:2])
# 使用一般bool索引，就会直接把满足条件的数据放进一维数组列举出来，如下：
print(arr[arr>50])
# 嵌套bool索引，下面以行作为示例
print(arr[2][arr[2]>50])# 将arr[2]当作b数组就可以理解了,统计数组第二行中的数据大于50
#如果是过滤列数据的话，也是差不多的，就是使用逗号分隔
print(arr[:,2][arr[:,2]>50])# 不加冒号居然报错



[[ 0 10 91 56 88 49]
 [22 30 93 41 98  6]
 [15 89 59  1  0 47]
 [11 68 36 31  8 98]]
41
41
[[22 30 93 41 98  6]
 [15 89 59  1  0 47]
 [11 68 36 31  8 98]]
[[ 0 91]
 [22 93]]
[91 56 88 93 98 89 59 68 98]
[89 59]
[91 93 59]


In [ ]:
# ndarray的计算
# 注意：原生的python如果使用列表的话，就没有这个加减乘除，使用列表加法的话就会变成这个拼接的操作
# 但是使用array定义的数组就可以加减乘除，对应位置的操作即可，
# 注意:数组与标量操作的话，每个元素都会操作一次
