In [ ]:
# 这是矩阵运算的广播机制
import numpy as np
#从右往左看，相同或者有一个是 1，就能广播，也就是说要么行数列数都相同，或者行数列数里面有一个是1
# 如果行数一个是2，一个是3就不行
a=np.array([2,3,4])
# 关于括号里的理解，1*3就是一行里面三个元素，一行的元素就可以放在一个括号里面
#b=np.array([2],[4],[6])
#下面才是三行一列的正确定义：
b=np.array([[2],
            [3],
            [4]])# 3*1，每一个元素就是一行，所以一个括号里面一个元素，只有一列所以最外层只有一个大括号
# 接下来就可以直接使用加法
# 记不住二维数组写法，可以分开写，容易记住
print(a+b)
c=np.array([
    [2,3],
    [3,9],
    [4,10]
])
# 简单写一个三维数组，就是几个二维数组叠加
d=np.array([[
    [2,3],
    [4,5],
    [6,8]]
    ,
    [[5,7],
    [9,10],
    [10,12]]
])
print(d)

[[4 5 6]
 [5 6 7]
 [6 7 8]]
[[[ 2  3]
  [ 4  5]
  [ 6  8]]

 [[ 5  7]
  [ 9 10]
  [10 12]]]


In [9]:
#矩阵乘法
a=np.array([
    [2,4],
    [3,6]
])
b=np.copy(a)
print(a*b)
# 注意：这里的乘法是每个元素对应位置的乘法，不是线性代数里面的乘法
# 线代里面的乘法使用@符号
print(a@b)

[[ 4 16]
 [ 9 36]]
[[16 32]
 [24 48]]


In [14]:
# 常见的数学函数操作
# 平方根sqrt,可以传入数字和列表以及数组
print(np.sqrt(9))
print(np.sqrt([1,4,9]))
# a=np.array([2,4,6],
#            [6,9,16],dtype=int)
# 创建一个二维数组应该都放进大列表里面
a=np.array([
    [2,3,4],
    [4,16,81]
])
print(np.sqrt(a))

# 计算指数exp函数，传入一个数字即可计算e^x
# 计算对数log函数，计算的是lnx
# 计算正弦，余弦以及正切，和数学一样，使用np.pi作为数值Π
print(np.tan(np.pi/4))

#绝对值函数不用多说，abs，也是可以传入列表的
# 计算a的b次方，使用power函数，可以传入列表

#四舍六入五取偶（意思就是小数点后一位为5的时候，需要向偶数对齐）,使用round函数
print(np.round([1.5,2.5,3.5,8.9,10.2]))

3.0
[1. 2. 3.]
[[1.41421356 1.73205081 2.        ]
 [2.         4.         9.        ]]
0.9999999999999999
[ 2.  2.  4.  9. 10.]


In [18]:
# 向上取整ceil（天花板），向下取整floor地板，也可以传入列表
print(np.ceil([1.2,3.5]))
print(np.floor([3.4,9.8]))

#缺失值isnan函数
print(np.isnan([1,2,np.nan,90]))

[2. 4.]
[3. 9.]
[False False  True False]


In [22]:
# 接下来就是一些数学函数
# sum是求和函数，平均函数是mean不是avg，都是可以操作数组的
# 计算中位数是median函数

# 计算方差就是var函数（差异），标准差就是方差开根号，使用std函数

#计算分位数，percentile函数，有两个参数（arr,10)意思就是arr中有10%的数字比它小，如果是50的话，就是中位数
# 关于分位数的计算方式，了解一下即可

# 下面介绍一下累积和与累积积，其实累积和就是前缀和使用函数cumsum，累积cumulative
# 累积积函数cumprod函数，就是前缀乘
arr=np.array([1,4,0,78])
print(np.cumsum(arr))
print(np.cumprod(arr))


[ 1  5  5 83]
[1 4 0 0]


In [33]:
# 比较函数，比较是否大于等于小于，逻辑与或非，检查数组之中是否有一个true或者全部是true，以及自定义条件
print(np.greater([1,4,5,8,9],6))
print(np.less([9,16,8,7],11))

# 是否等于就是equal函数，也是两个参数,两个参数也可以是矩阵
print(np.equal([[2,3,4],[6,9,10]],[2,6,4]))

# 逻辑与或非，就是logical_and之类的，也可以传入两个数组


# 检查元素至少一个为True返回真的函数：any
print(np.any([1,0,0,0,0]))
# 检查所有元素都为真才返回True的函数：all
print(np.all([0,0,0,0,4,5]))

[False False False  True  True]
[ True False  True  True]
[[ True False  True]
 [False False False]]
True
False


In [37]:
# 自定义条件where函数，格式np.where(条件，符合条件，不符合条件)
arr=np.array([1,5,7,8,10])
# 第一个例子就是符合条件的直接使用arr原元素即可，不符合条件的使用-1代替
# 第二个例子就是符合条件的直接使用10代替
print(np.where(arr>6,arr,-1))
print(np.where(arr>6,10,-1))

# 合理使用where还可以在第三个参数再写where，就可以形成if-else if-else的操作了


#select函数也可以实现同样的操作
import numpy as np

arr = np.array([45, 60, 75, 90])

conditions = [
    arr < 60,
    (arr >= 60) & (arr < 80),
    arr >= 80
]

choices = [
    "不及格",
    "及格",
    "优秀"
]

result = np.select(conditions, choices, default="未知")# 要有default，这是默认操作

print(result)

[-1 -1  7  8 10]
[-1 -1 10 10 10]
['不及格' '及格' '及格' '优秀']


In [45]:
# 排序函数sort
np.random.seed(0)
arr=np.random.randint(0,1000,30)
print(arr)
# arr.sort()# 这个函数会改变原来的arr数组
print(arr)
print(np.sort(arr))# 这个函数就不会改变原来的数组
# print(arr)
print(np.argsort(arr))# 将排序之后的数组以下标的形式显示出来了

#去掉重复就是np.unique()函数

[684 559 629 192 835 763 707 359   9 723 277 754 804 599  70 472 600 396
 314 705 486 551  87 174 600 849 677 537 845  72]
[684 559 629 192 835 763 707 359   9 723 277 754 804 599  70 472 600 396
 314 705 486 551  87 174 600 849 677 537 845  72]
[  9  70  72  87 174 192 277 314 359 396 472 486 537 551 559 599 600 600
 629 677 684 705 707 723 754 763 804 835 845 849]
[ 8 14 29 22 23  3 10 18  7 17 15 20 27 21  1 13 24 16  2 26  0 19  6  9
 11  5 12  4 28 25]


In [85]:
# 拼接函数
arr1=[1,3,5]
arr2=[9,8,10]
# arr1=np.array([[1,3,5]])
# arr2=np.array([[9,8,10]])
# print(np.concatenate(arr1,arr2)),这种定义是错误的，需要在加上一个小括号
print(np.concatenate((arr1,arr2)))# 加上两个小括号，表示这两个list为一组拼接
print(np.concatenate([arr1,arr2],axis=0))# 不好理解，使用中括号也可以,0是列所以是竖着拼，1是行，所以横着拼
arr=np.random.randint(0,1000,30)
# 数组的分割split函数，可以分成几段
print(np.split(arr,5))
print(np.split(arr,[6,10,13]))# 也可以按照指定位置分割，自己填入列表即可

[ 1  3  5  9  8 10]
[ 1  3  5  9  8 10]
[array([ 11, 616, 212, 138, 694, 421], dtype=int32), array([637, 668, 623, 488, 770, 539], dtype=int32), array([979, 217, 663, 821, 307, 174], dtype=int32), array([148, 949, 541, 579, 547, 807], dtype=int32), array([393,  73, 297, 919, 899, 814], dtype=int32)]
[array([ 11, 616, 212, 138, 694, 421], dtype=int32), array([637, 668, 623, 488], dtype=int32), array([770, 539, 979], dtype=int32), array([217, 663, 821, 307, 174, 148, 949, 541, 579, 547, 807, 393,  73,
       297, 919, 899, 814], dtype=int32)]


In [52]:
# 整形函数reshape
print(np.reshape(arr,[5,6]))

[[684 559 629 192 835 763]
 [707 359   9 723 277 754]
 [804 599  70 472 600 396]
 [314 705 486 551  87 174]
 [600 849 677 537 845  72]]


In [ ]:
# 气温例子：
temps=[28,30,29,32,30,27,26]
temps=np.array([28,30,29,32,30,27,26])
# 简单介绍一下带f的保留3位小数点打法
print(f"平均气温：{np.mean(temps):.3f}")# 记住这种格式即可
print(np.sum(temps>30))# 因为普通列表不支持这种“每个元素分别比较”的操作,所以这里temps必须为数组

平均气温：28.857
1


In [68]:
# 获取数组行数与列数，shape获取的是形状，返回的是数组，下标0是行，1是列
np.random.seed(0)
arr=np.random.randint(0,10,(3,4))
print(arr)
# 如何获取每一行或者每一列的最大最小值呢？
for i in range(0,arr.shape[1]):
    print(f"第{i+1}列的最大值是：{np.max(arr[:,i:i+1])}，最小值是：{
        np.min(arr[:,i:i+1])  # 其实想要取每一列，可以不用加上冒号，直接在列的位置写上一个数字即可（不用加上冒号：）
    }")
for i in range(0,arr.shape[0]):
    print(f"第{i+1}行的最大值是：{np.max(arr[i:i+1,:])}，最小值是：{np.min(arr[i:i+1,:])}")


# 我去，居然还有高手，就是数组里面有一个参数axis，可以指定行或者列(axis=0是列，1是行)
print(np.max(arr,axis=0),np.min(arr,axis=0),sep="->")
print(np.max(arr,axis=1),np.min(arr,axis=1),sep="->")

#所有为奇数的元素修改为-1
arr[arr%2==1]=-1
print(arr)




[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
第1列的最大值是：7，最小值是：2
第2列的最大值是：9，最小值是：0
第3列的最大值是：7，最小值是：3
第4列的最大值是：6，最小值是：3
第1行的最大值是：5，最小值是：0
第2行的最大值是：9，最小值是：3
第3行的最大值是：7，最小值是：2
[7 9 7 6]->[2 0 3 3]
[5 9 7]->[0 3 2]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


In [69]:
# 找到一个数组中的最大最小值的下标，本来是使用max与min的，但是要找下标的话，就需要加上arg前缀了
arr=[1,2,3,90,67]
print(np.argmax(arr)+1)

4
